name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B test

      - name: Run tests with coverage
        run: mvn verify -P coverage

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODECOV_TOKEN }}
          coverage-reports: ./bpjs-debugger/target/site/jacoco/jacoco.xml,./service/target/site/jacoco/jacoco.xml,./controller/target/site/jacoco/jacoco.xml